### ISSUE TITLE
Add a Preloader while the NFT Cards load

### ISSUE THREAD

**Issue by bhupendra-chouhan** [Rise-In/NFT-Minter#13]
# Task:
- [x] Display a preloader animation after the user clicks the `Connect Wallet` button, and keep it visible while the NFT cards are loading.

**Comment by saidarshan27** [comment]
I have already added a Loading text in the search functionality pull request? do you want a spinning animation instead??

**Comment by bhupendra-chouhan** [comment]
Yes!! Add a spinning animation as a preloader.
